ci: added test report and test coverage reports to CI

diff --git a/.github/workflows/gradleBuild.yml b/.github/workflows/gradleBuild.yml
--- a/.github/workflows/gradleBuild.yml
+++ b/.github/workflows/gradleBuild.yml
@@ -21,5 +21,33 @@ jobs:
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
 
-      - name: Execute Gradle build
-        run: ./gradlew build
+      - name: Execute Gradle assemble
+        run: ./gradlew assemble
+
+      - name: Execute tests
+        run: ./gradlew test
+      - name: Test Summary
+        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86
+        with:
+          paths: "**/test-results/**/TEST-*.xml"
+        if: always()
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@27bb264e040efceeae9469a5956785c27c6997f4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          token: ${{ secrets.GITHUB_TOKEN }}
+          comment: true
+          updateComment: true
+
+      - name: Code Coverage
+        id: jacoco
+        uses: madrapps/jacoco-report@cae93f61ea553f8babe9d8c1e365c1ce5cece922
+        with:
+          paths: ${{github.workspace}}/**/spha-cli/build/reports/tests/test/index.html
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: '75'
+          min-coverage-changed-files: '75'
+          title: Code Coverage
+          update-comment: true
